### ISSUE TITLE
How to play SpotX Add every 5 minute while user is watching app video?

### ISSUE THREAD

**Issue by primeappsin** [spotxmobile/spotx-demo-ios#2]
Hi 
I have iOS app in App Store. We are playing live event but I want to present spots add very 5 minute. But when app will open than video will pause & resume automatically.

**Comment by scottjulian** [comment]
You can easily set an NSTimer interval to keep track when 5 minutes has passed. Then just follow the documentation to show a video advertisement. Then just repeat that every 5 minutes.

**Comment by primeappsin** [comment]
NSTimer is not good solution, I can use timer but how can I manage original player which play my event?

**Comment by scottjulian** [comment]
This is not an issue with the SDK so I am keeping this closed. You are asking for how to implement a feature to your app that is outside the scope of the SDK.
